theme = "tokyonight_storm"

[editor]
line-number = "relative"
rulers = [100]
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[keys.normal]
C-g = ":toggle-option indent-guides.render"

# naviagate entire pane up/down 1 line
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]

# naviate entire pane up/down by half page
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]

# move lines up/down (works if multiple lines selected) (doesn't work with cursors on multiple lines)
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.normal."["]
"[" = "goto_previous_buffer"

[keys.normal."]"]
"]" = "goto_next_buffer"

